name: calendar sync

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: create config
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - run: |
      cp config /github/home/.config/calcurse/caldav/config


    - name: Run sync
      uses: docker://publicrant/streamlit-test

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply calendar changes